#!/bin/sh
#
# Simple wrapper for executing ansible-playbook with local connection.
#
# USAGE:
#    ansible-playbook-wrapper  [other ansible-playbook arguments]
#
# ENVIRONMENT VARIABLES:
# 
#    - PLAYBOOK: playbook filename;   default = "playbook.yml"
#    - INVENTORY: inventory filename; default = "/etc/ansible/hosts"
#    - REQUIREMENTS: requirements filename; default = "requirements.yml"
#


if [ -z "$PLAYBOOK" ]; then
    PLAYBOOK=playbook.yml
fi


if [ -z "$REQUIREMENTS" ]; then
    exec ansible-galaxy          \
    install -r $REQUIREMENTS          \
       "$@"
fi

if [ -z "$INVENTORY" ]; then
    exec ansible-playbook        \
       $PLAYBOOK                 \
       --connection=local        \
       "$@"
else
    exec ansible-playbook        \
       -i $INVENTORY  $PLAYBOOK  \
       --connection=local        \
       "$@"
fi

